# https://taskfile.dev

version: '3'

tasks:
  cipra:
    cmds:
      - jekyll s -s src
  zbasu:
    cmds:
      - task: jdikygau
      - task: zbasu-poho
  zbasu-poho:
    cmds:
      - jekyll b -s src
  jdikygau:
    cmds:
      - python distiller.py jbovlaste-en.xml > src/vlaste.json